
# ---- BEGIN Pipeline definitions generated by Pipeline.py DO NOT EDIT

const seq.endian = BIG
const seq.width = 56

field seq.op = 0:1
field seq.address_mux = 2:3
field seq.condition = 4:7
field ax = 8:10
field bx = 11:12
field cx = 13:15
field csx = 16:17
field dx = 18:20
field ex = 21:23
field ox = 24:24
field px = 25:27
field qx = 28:29
field rrx = 30:30
field sx = 31:34
field ende = 35:35
field testa = 36:36
field wd_en = 37:37
field trap = 38:38
field uc_debug = 39:39
field write_size = 40:41
field __unused = 42:43
field seq.address = 44:55
field _const12 = 44:55

const AXNONE = 0
const AXCONST = 1
const AXE = 2
const AXR = 3
const AXRR = 4
const AXS = 5
const BXNONE = 0
const BXCONST = 1
const BXS = 2
const CXNONE = 0
const CXCONST = 1
const CXMB = 2
const CXRR = 3
const CXS = 4
const CSXNONE = 0
const CSXCONST = 1
const CSXK00 = 2
const DXNONE = 0
const DXCONST = 1
const DXC = 2
const DXCC = 3
const DXNC = 4
const DXPSW1 = 5
const DXPSW2 = 6
const EXNONE = 0
const EXCONST = 1
const EXB = 1
const EXCC = 2
const EXS = 3
const OXNONE = 0
const OXC = 1
const PXNONE = 0
const PXCONST = 1
const PXQ = 2
const PXS = 3
const PCTP1 = 4
const QXNONE = 0
const QXCONST = 1
const QXP = 2
const RRXNONE = 0
const RRXS = 1
const SXADD = 0
const SXXOR = 1
const SXOR = 2
const SXAND = 3
const SXMA = 4
const SXMD = 5
const SXUAB = 6
const SXUAH = 7
const SXUDB = 8
const SXUDH = 9
const SXA = 10
const SXB = 11
const SXD = 12
const SXP = 13
const ADDR_MUX_SEQ = 0
const ADDR_MUX_OPCODE = 1
const ADDR_MUX_OPROM = 2
const COND_NONE = 0
const COND_CC_ZERO = 1
const COND_CC_NEG = 2
const COND_CC_POS = 3
const WR_NONE = 0
const WR_BYTE = 1
const WR_HALF = 2
const WR_WORD = 3

# ---- END Pipeline definitions generated by Pipeline.py DO NOT EDIT

def main:
    call message
    call countdown
    call fib
    uc_debug = 1
    trap = 1

def message:
    _const12 = 'H', ax = AXCONST
    sx = SXA, _const12 = 'i', ax = AXCONST, wd_en=1
    sx = SXA, _const12 = '!', ax = AXCONST, wd_en=1
    sx = SXA, _const12 = '\n', ax = AXCONST, wd_en=1
    sx = SXA, wd_en=1, return

def countdown:
    _const12 = 0, ax = AXCONST
    _const12 = 0, ax = AXCONST
    _const12 = 5, ax = AXCONST
    _const12 = -1, dx = DXCONST, testa = 1
    do:
        sx = SXADD, ax = AXS, testa = 1, uc_debug = 1
    while COND_CC_POS
    _const12 = 99, ax = AXCONST, return

def fib:
    _const12 = 0, ax = AXCONST, cx = CXCONST, dx = DXCONST
    _const12 = 0, ax = AXCONST, cx = CXCONST, dx = DXCONST
    _const12 = 1, ax = AXCONST, cx = CXCONST, dx = DXCONST
    do:
        sx = SXADD, cx = CXS, uc_debug=1, testa = 1
        sx = SXD, ax = AXS, dx = DXC
    while COND_CC_POS
    sx = SXADD, uc_debug=1
    sx = SXADD, return
