
# ---- BEGIN Pipeline definitions generated by Pipeline.py DO NOT EDIT

const seq.endian = BIG
const seq.width = 56

field seq.op = 0:1
field seq.address_mux = 2:3
field seq.condition = 4:7
field ax = 8:10
field bx = 11:12
field cx = 13:15
field csx = 16:17
field dx = 18:20
field ex = 21:23
field lmx = 24:25
field px = 26:28
field qx = 29:30
field rrx = 31:31
field sx = 32:35
field ende = 36:36
field testa = 37:37
field wd_en = 38:38
field trap = 39:39
field uc_debug = 40:40
field write_size = 41:42
field __unused = 43:43
field seq.address = 44:55
field _const12 = 44:55

const AXNONE = 0
const AXCONST = 1
const AXE = 2
const AXR = 3
const AXRR = 4
const AXS = 5
const AXRR0 = 6
const BXNONE = 0
const BXCONST = 1
const BXS = 2
const CXNONE = 0
const CXCONST = 1
const CXMB = 2
const CXRR = 3
const CXS = 4
const CSXNONE = 0
const CSXCONST = 1
const CSXK00 = 2
const DXNONE = 0
const DXCONST = 1
const DXC = 2
const DXCC = 3
const DXNC = 4
const DXPSW1 = 5
const DXPSW2 = 6
const EXNONE = 0
const EXCONST = 1
const EXB = 1
const EXCC = 2
const EXS = 3
const LMXQ = 0
const LMXP = 1
const LMXC = 2
const PXNONE = 0
const PXCONST = 1
const PXQ = 2
const PXS = 3
const PCTP1 = 4
const QXNONE = 0
const QXCONST = 1
const QXP = 2
const RRXNONE = 0
const RRXS = 1
const SXADD = 0
const SXXOR = 1
const SXOR = 2
const SXAND = 3
const SXMA = 4
const SXMD = 5
const SXUAB = 6
const SXUAH = 7
const SXUDB = 8
const SXUDH = 9
const SXA = 10
const SXB = 11
const SXD = 12
const SXP = 13
const ADDR_MUX_SEQ = 0
const ADDR_MUX_OPCODE = 1
const ADDR_MUX_OPROM = 2
const COND_NONE = 0
const COND_CC_ZERO = 1
const COND_CC_NEG = 2
const COND_CC_POS = 3
const COND_OP_INDIRECT = 4
const COND_OP_INDEX = 5
const WR_NONE = 0
const WR_BYTE = 1
const WR_HALF = 2
const WR_WORD = 3

# ---- END Pipeline definitions generated by Pipeline.py DO NOT EDIT

def main:
    call sigma

    trap = 1

def sigma:
    call reset

    prep: lmx = LMXC, qx = QXP, if COND_OP_INDIRECT:
        cx = CXMB, dx = DXC
    sx = SXADD, px = PXS, switch ADDR_MUX_OPCODE:
        OP_NAO_00:
            trap = 1

        OP_NAO_01:
            trap = 1

        OP_LCFI:
            px = PXQ, lmx = LMXQ
            cx = CXMB, dx = DXC, px = PCTP1, ende = 1, continue prep

        OP_NAO_03:
            trap = 1

        OP_CAL1:
            trap = 1

        OP_CAL2:
            trap = 1

        OP_CAL3:
            trap = 1

        OP_CAL4:
            trap = 1

        OP_PLW:
            trap = 1

        OP_PSW:
            trap = 1

        OP_PLM:
            trap = 1

        OP_PSM:
            trap = 1

        OP_NAO_0c:
            trap = 1

        OP_NAO_0d:
            trap = 1

        OP_LPSD:
            trap = 1

        OP_XPSD:
            trap = 1

        OP_AD:
            trap = 1

        OP_CD:
            trap = 1

        OP_LD:
            trap = 1

        OP_MSP:
            trap = 1

        OP_NAO_14:
            trap = 1

        OP_STD:
            trap = 1

        OP_NAO_16:
            trap = 1

        OP_NAO_17:
            trap = 1

        OP_SD:
            trap = 1

        OP_CLM:
            trap = 1

        OP_LCD:
            trap = 1

        OP_LAD:
            trap = 1

        OP_FSL:
            trap = 1

        OP_FAL:
            trap = 1

        OP_FDL:
            trap = 1

        OP_FML:
            trap = 1

        OP_AI:
            trap = 1

        OP_CI:
            trap = 1

        OP_LI:
            trap = 1

        OP_MI:
            trap = 1

        OP_SF:
            trap = 1

        OP_S:
            trap = 1

        OP_NAO_26:
            trap = 1

        OP_NAO_27:
            trap = 1

        OP_CVS:
            trap = 1

        OP_CVA:
            trap = 1

        OP_LM:
            trap = 1

        OP_STM:
            trap = 1

        OP_NAO_2c:
            trap = 1

        OP_NAO_2d:
            trap = 1

        OP_WAIT:
            trap = 1

        OP_LRP:
            trap = 1

        OP_AW:
            trap = 1

        OP_CW:
            trap = 1

        OP_LW:
            lmx = LMXP
            cx = CXMB, dx = DXC
            sx = SXD, rrx = RRXS, ax = AXS, lmx = LMXQ, px = PXQ
            testa = 1, cx = CXMB, dx = DXC, px = PCTP1, ende = 1, continue prep

        OP_MTW:
            trap = 1

        OP_NAO_34:
            trap = 1

        OP_STW:
            trap = 1

        OP_DW:
            trap = 1

        OP_MW:
            trap = 1

        OP_SW:
            trap = 1

        OP_CLR:
            trap = 1

        OP_LCW:
            trap = 1

        OP_LAW:
            trap = 1

        OP_FSS:
            trap = 1

        OP_FAS:
            trap = 1

        OP_FDS:
            trap = 1

        OP_FMS:
            trap = 1

        OP_TTBS:
            trap = 1

        OP_TBS:
            trap = 1

        OP_NAO_42:
            trap = 1

        OP_NAO_43:
            trap = 1

        OP_ANLZ:
            trap = 1

        OP_CS:
            trap = 1

        OP_XW:
            trap = 1

        OP_STS:
            trap = 1

        OP_EOR:
            trap = 1

        OP_OR:
            trap = 1

        OP_LS:
            trap = 1

        OP_AND:
            trap = 1

        OP_SIO:
            sx = SXP, bx = BXS, ax = AXRR0
            _const12 = 0, px = PXCONST # B contains IO address
            _const12 = 0x80, px = PXCONST
            sx = SXA, lmx = LMXP, write_size = WR_WORD
            px = PXQ, lmx = LMXQ
            cx = CXMB, dx = DXC, px = PCTP1, ende = 1, continue prep

        OP_TIO:
            px = PXQ, lmx = LMXQ
            cx = CXMB, dx = DXC, px = PCTP1, ende = 1, continue prep

        OP_TDV:
            trap = 1

        OP_HIO:
            trap = 1

        OP_AH:
            trap = 1

        OP_CH:
            trap = 1

        OP_LH:
            trap = 1

        OP_MTH:
            trap = 1

        OP_NAO_54:
            trap = 1

        OP_STH:
            trap = 1

        OP_DH:
            trap = 1

        OP_MH:
            trap = 1

        OP_SH:
            trap = 1

        OP_NAO_59:
            trap = 1

        OP_LCH:
            trap = 1

        OP_LAH:
            trap = 1

        OP_NAO_5c:
            trap = 1

        OP_NAO_5d:
            trap = 1

        OP_NAO_5e:
            trap = 1

        OP_NAO_5f:
            trap = 1

        OP_CBS:
            trap = 1

        OP_MBS:
            trap = 1

        OP_NAO_62:
            trap = 1

        OP_EBS:
            trap = 1

        OP_BDR:
            trap = 1

        OP_BIR:
            trap = 1

        OP_AWM:
            trap = 1

        OP_EXU:
            trap = 1

        OP_BCR:
            trap = 1

        OP_BCS:
            px = PXQ, lmx = LMXQ
            cx = CXMB, dx = DXC, px = PCTP1, ende = 1, continue prep

        OP_BAL:
            trap = 1

        OP_INT:
            trap = 1

        OP_RD:
            trap = 1

        OP_WD:
            trap = 1

        OP_AIO:
            trap = 1

        OP_MMC:
            trap = 1

        OP_LCF:
            trap = 1

        OP_CB:
            trap = 1

        OP_LB:
            trap = 1

        OP_MTB:
            trap = 1

        OP_STFC:
            trap = 1

        OP_STB:
            trap = 1

        OP_PACK:
            trap = 1

        OP_UNPK:
            trap = 1

        OP_DS:
            trap = 1

        OP_DA:
            trap = 1

        OP_DD:
            trap = 1

        OP_DM:
            trap = 1

        OP_DSA:
            trap = 1

        OP_DC:
            trap = 1

        OP_DL:
            trap = 1

        OP_DST:
            trap = 1

def test_prep:
    _const12 = (0x00120026 >> 24) & 0xfff, cx = CXCONST
    _const12 = (0x00120026 >> 12) & 0xfff, cx = CXCONST
    _const12 = 0x26, cx = CXCONST
    ende = 1
    _const12 = 0, ax = AXCONST
    _const12 = 0, ax = AXCONST
    _const12 = 16, ax = AXCONST
    sx = SXA, rrx = RRXS
    _const12 = 0, ax = AXCONST

    # No indirect, no index
    _const12 = 0, cx = CXCONST
    _const12 = 0, cx = CXCONST
    _const12 = 0x26, cx = CXCONST
    ende = 1
    dx = DXC, call prep_func

    # Indirect
    _const12 = (0x80000026 >> 24) & 0xfff, cx = CXCONST
    _const12 = (0x80000026 >> 12) & 0xfff, cx = CXCONST
    _const12 = 0x26, cx = CXCONST
    ende = 1
    dx = DXC, call prep_func

    # Indexed
    _const12 = (0x00120026 >> 24) & 0xfff, cx = CXCONST
    _const12 = (0x00120026 >> 12) & 0xfff, cx = CXCONST
    _const12 = 0x26, cx = CXCONST
    ende = 1
    dx = DXC, call prep_func

    # Indirect, indexed
    _const12 = (0x80120026 >> 24) & 0xfff, cx = CXCONST
    _const12 = (0x80120026 >> 12) & 0xfff, cx = CXCONST
    _const12 = 0x26, cx = CXCONST
    ende = 1
    dx = DXC, call prep_func
    return

def prep_func:
    lmx = LMXC, qx = QXP, if COND_OP_INDIRECT:
        cx = CXMB, dx = DXC
    sx = SXADD, px = PXS
    uc_debug = 1, return

# See 3-658
def reset:
    # D contains a no-op instruction, e.g. LCFI, 0 0
    _const12 = (0x02000000 >> 24) & 0xfff, dx = DXCONST
    _const12 = (0x02000000 >> 12) & 0xfff, dx = DXCONST
    _const12 = (0x02000000 >> 00) & 0xfff, dx = DXCONST
    # Q contains address 0x25, the reset vector
    _const12 = (0x00000025 >> 24) & 0xfff, qx = QXCONST
    _const12 = (0x00000025 >> 12) & 0xfff, qx = QXCONST
    _const12 = (0x00000025 >> 00) & 0xfff, qx = QXCONST
    # Load P with reset vector, load C with no-op instruction
    px = PXQ, sx = SXD, cx = CXS
    # Force ENDE, increment P, save in Q to simulate instruction execution
    px = PCTP1, ende = 1
    qx = QXP, return

def fetch:
    cx = CXMB, dx = DXC, px = PCTP1, lmx = LMXC, ende = 1, uc_debug = 1, return

def message:
    _const12 = 'H', ax = AXCONST
    sx = SXA, _const12 = 'i', ax = AXCONST, wd_en=1
    sx = SXA, _const12 = '!', ax = AXCONST, wd_en=1
    sx = SXA, _const12 = '\n', ax = AXCONST, wd_en=1
    sx = SXA, wd_en=1, return

def countdown:
    _const12 = 0, ax = AXCONST
    _const12 = 0, ax = AXCONST
    _const12 = 5, ax = AXCONST
    _const12 = -1, dx = DXCONST
    _const12 = -1, dx = DXCONST
    _const12 = -1, dx = DXCONST, testa = 1
    do:
        sx = SXADD, ax = AXS, testa = 1, uc_debug = 1
    while COND_CC_POS
    _const12 = 99, ax = AXCONST, return

def fib:
    _const12 = 0, ax = AXCONST, cx = CXCONST, dx = DXCONST
    _const12 = 0, ax = AXCONST, cx = CXCONST, dx = DXCONST
    _const12 = 1, ax = AXCONST, cx = CXCONST, dx = DXCONST
    do:
        sx = SXADD, cx = CXS, uc_debug=1, testa = 1
        sx = SXD, ax = AXS, dx = DXC
    while COND_CC_POS
    sx = SXADD, uc_debug=1
    sx = SXADD, return

const OP_NAO_00 = 0
const OP_NAO_01 = 1
const OP_LCFI = 2
const OP_NAO_03 = 3
const OP_CAL1 = 4
const OP_CAL2 = 5
const OP_CAL3 = 6
const OP_CAL4 = 7
const OP_PLW = 8
const OP_PSW = 9
const OP_PLM = 10
const OP_PSM = 11
const OP_NAO_0c = 12
const OP_NAO_0d = 13
const OP_LPSD = 14
const OP_XPSD = 15
const OP_AD = 16
const OP_CD = 17
const OP_LD = 18
const OP_MSP = 19
const OP_NAO_14 = 20
const OP_STD = 21
const OP_NAO_16 = 22
const OP_NAO_17 = 23
const OP_SD = 24
const OP_CLM = 25
const OP_LCD = 26
const OP_LAD = 27
const OP_FSL = 28
const OP_FAL = 29
const OP_FDL = 30
const OP_FML = 31
const OP_AI = 32
const OP_CI = 33
const OP_LI = 34
const OP_MI = 35
const OP_SF = 36
const OP_S = 37
const OP_NAO_26 = 38
const OP_NAO_27 = 39
const OP_CVS = 40
const OP_CVA = 41
const OP_LM = 42
const OP_STM = 43
const OP_NAO_2c = 44
const OP_NAO_2d = 45
const OP_WAIT = 46
const OP_LRP = 47
const OP_AW = 48
const OP_CW = 49
const OP_LW = 50
const OP_MTW = 51
const OP_NAO_34 = 52
const OP_STW = 53
const OP_DW = 54
const OP_MW = 55
const OP_SW = 56
const OP_CLR = 57
const OP_LCW = 58
const OP_LAW = 59
const OP_FSS = 60
const OP_FAS = 61
const OP_FDS = 62
const OP_FMS = 63
const OP_TTBS = 64
const OP_TBS = 65
const OP_NAO_42 = 66
const OP_NAO_43 = 67
const OP_ANLZ = 68
const OP_CS = 69
const OP_XW = 70
const OP_STS = 71
const OP_EOR = 72
const OP_OR = 73
const OP_LS = 74
const OP_AND = 75
const OP_SIO = 76
const OP_TIO = 77
const OP_TDV = 78
const OP_HIO = 79
const OP_AH = 80
const OP_CH = 81
const OP_LH = 82
const OP_MTH = 83
const OP_NAO_54 = 84
const OP_STH = 85
const OP_DH = 86
const OP_MH = 87
const OP_SH = 88
const OP_NAO_59 = 89
const OP_LCH = 90
const OP_LAH = 91
const OP_NAO_5c = 92
const OP_NAO_5d = 93
const OP_NAO_5e = 94
const OP_NAO_5f = 95
const OP_CBS = 96
const OP_MBS = 97
const OP_NAO_62 = 98
const OP_EBS = 99
const OP_BDR = 100
const OP_BIR = 101
const OP_AWM = 102
const OP_EXU = 103
const OP_BCR = 104
const OP_BCS = 105
const OP_BAL = 106
const OP_INT = 107
const OP_RD = 108
const OP_WD = 109
const OP_AIO = 110
const OP_MMC = 111
const OP_LCF = 112
const OP_CB = 113
const OP_LB = 114
const OP_MTB = 115
const OP_STFC = 116
const OP_STB = 117
const OP_PACK = 118
const OP_UNPK = 119
const OP_DS = 120
const OP_DA = 121
const OP_DD = 122
const OP_DM = 123
const OP_DSA = 124
const OP_DC = 125
const OP_DL = 126
const OP_DST = 127
